options:
    prefix: &d&lUniversal&5&lPR &8»


command /globalbooster [<text>] [<text>] [<integer>] [<player>]:
    permission: admin.core
    aliases: /gb
    trigger:
        if arg-1 is "stop":
            if arg-2 is "money":
                if {globalboostermoney} is not set:
                    send "&5&l(!) &dThere is not a global money booster active!"
                if {globalboostermoney} is set:
                    clear {globalboostermoney} 
                    clear {globalboostertimeleft}
                    broadcast "{@prefix} &dThe global money booster has stopped"
            if arg-2 is "token":
                if {globalboostertoken} is not set:
                    send "&5&l(!) &dThere is not a global token booster active!"
                if {globalboostertoken} is set:
                    clear {globalboostertoken} 
                    clear {globalboostertokentimeleft}
                    broadcast "{@prefix} &dThe global token booster has stopped"
        loop all players:
            wait 10 ticks
            execute command "scoreboardrl %loop-player%"
        if arg-1 is "start":
            if arg-2 is "token":
                if {globalboostertoken} is set:
                    send "&5&l(!) &dThere is a global token booster active!"
                if {globalboostertoken} is not set:
                    if executor is console:
                        set {globalboostertoken} to arg-3
                        broadcast "{@prefix} &r&l%arg-4% &dhas started a global token booster for &r&l%arg-3% Minutes"
                    if executor is player:
                        set {globalboostertoken} to arg-3
                        broadcast "{@prefix} &r&l%player% &dhas started a global token booster for &r&l%arg-3% Minutes"
            if arg-2 is "money":
                if {globalboostermoney} is set:
                    send "&5&l(!) &dThere is a global money booster active!"
                if {globalboostermoney} is not set:
                    if executor is console:
                        set {globalboostermoney} to arg-3
                        broadcast "{@prefix} &r&l%arg-4% &dhas started a global money booster for &r&l%arg-3% Minutes"
                    if executor is player:
                        set {globalboostermoney} to arg-3
                        broadcast "{@prefix} &r&l%player% &dhas started a global money booster for &r&l%arg-3% Minutes"













            loop all players:
                execute command "scoreboardrl %loop-player%"




        if arg-1 is "give":
            if arg-2 is "money":
                if arg-3 is 30:
                    give arg-4 glowing book named "&d30 Minute &r&lGlobal Money Booster" with lore "&7Click me to start a global booster (Wont work if one is already enabled)"
                if arg-3 is 60:
                    give arg-4 glowing book named "&d60 Minute &r&lGlobal Money Booster" with lore "&7Click me to start a global booster (Wont work if one is already enabled)"
            if arg-2 is "token":
                if arg-3 is 30:
                    give arg-4 glowing book named "&d30 Minute &r&lGlobal Token Booster" with lore "&7Click me to start a global booster (Wont work if one is already enabled)"
                if arg-3 is 60:
                    give arg-4 glowing book named "&d60 Minute &r&lGlobal Token Booster" with lore "&7Click me to start a global booster (Wont work if one is already enabled)"




every minute:
    if {globalboostermoney} is more than 0:
        remove 1 from {globalboostermoney}
        loop all players:
            execute command "scoreboardrl %loop-player%"
            stop
    if {globalboostermoney} is 0:
        execute command "globalbooster stop money"
    if {globalboostertoken} is more than 0:
        remove 1 from {globalboostertoken}
        loop all players:
            execute command "scoreboardrl %loop-player%"
            stop
    if {globalboostertoken} is 0:
        execute command "globalbooster stop token"




on death:
    if attacker is not player:
        set death message to "&5&l(!) &r&l%player% &dis out!"


on rightclick:
    name of player's tool is "&d60 Minute &r&lGlobal Token Booster":
        remove player's held item from player's inventory
        if {globalboostertoken} is set:
            send "&5&l(!) &dA Global Token Booster is already active!" to player
        if {globalboostertoken} is not set:
            send "&5&l(!) &dYou have activated a global token booster!" to player
            execute command "globalbooster start token 60 %player%"
    name of player's tool is "&d30 Minute &r&lGlobal Token Booster":
        remove player's held item from player's inventory
        if {globalboostertoken} is set:
            send "&5&l(!) &dA Global Token Booster is already active!" to player
        if {globalboostertoken} is not set:
            send "&5&l(!) &dYou have activated a global token booster!" to player
            execute command "globalbooster start token 30 %player%"
    name of player's tool is "&d30 Minute &r&lGlobal Money Booster":
        remove player's held item from player's inventory
        if {globalboostermoney} is set:
            send "&5&l(!) &dA Global Money Booster is already active!" to player
        if {globalboostermoney} is not set:
            send "&5&l(!) &dYou have activated a global money booster!" to player
            execute command "globalbooster start money 30 %player%"
    name of player's tool is "&d60 Minute &r&lGlobal Money Booster":
        remove player's held item from player's inventory
        if {globalboostermoney} is set:
            send "&5&l(!) &dA Global Money Booster is already active!" to player
        if {globalboostermoney} is not set:
            send "&5&l(!) &dYou have activated a global money booster!" to player
            execute command "globalbooster start money 60 %player%"











       
on hunger meter change:
    cancel event

on join:
    if {token::%player's uuid%} is less than 0:
        set {token::%player's uuid%} to 0


on death:
    if attacker is a player:
        set death message to "&5&l(!) &r&l%player% &dhas been killed by &r&l%attacker%"
     
on block break:
    if event-block is sponge:
        stop
    if world of player is "season2":
        if level of infinity of player's tool is more than 0:
            set {cratexD::%player%} to level of infinity of player's tool
            set {cratechance::%player%} to {cratexD::%player%}*.01984273987473284927349828734
            chance of {cratechance::%player%}%:
                set {cratechance::%player%} to random integer between 1 and 100
                if {cratechance::%player%} is between 1 and 74:
                    execute command "/key give %player% common 1 silent"
                if {cratechance::%player%} is between 76 and 88:
                    execute command "/key give %player% uncommon 1 silent"
                if {cratechance::%player%} is between 89 and 95:
                    execute command "/key give %player% rare 1 silent"
                if {cratechance::%player%} is between 96 and 100:
                    execute command "/key give %player% epic 1 silent"
                     

        clear {loopblock::%player%}
        if player's tool is diamond pickaxe:
            enchant player's tool with "Flame %level of flame of player's tool + 1%" parsed as enchantment type
            set {blocks::%player's uuid%} to "%level of flame of player's tool + 1%"
            set 3rd line of lore of player's tool to "&7Blocks Mined %{blocks::%player's uuid%}%"

        if level of unbreaking of player's tool is more than 0:
            chance of .349843579843757439875743985839834587243905874390584390%:
                if {globalboostertoken} is set:
                    set {luckyrandom::%player%} to random number between 1000 and 3200
                    set {luckyrandom::%player%} to {luckyrandom::%player%}*level of unbreaking of tool of player*2
                    send "{@prefix} &r&lLucky &dhas given you %formatNum({luckyrandom::%player%})%&d tokens"
                    add {luckyrandom::%player%} to {token::%player's uuid%}
                    stop
                set {luckyrandom::%player%} to random number between 1000 and 3200
                set {luckyrandom::%player%} to {luckyrandom::%player%}*level of unbreaking of tool of player
                send "{@prefix} &r&lLucky &dhas given you %formatNum({luckyrandom::%player%})%&d tokens"
                add {luckyrandom::%player%} to {token::%player's uuid%}
        if level of riptide of player's tool is more than 0:
            set {charityxD::%player%} to level of riptide of player's tool
            set {charityxD::%player%} to {charityxD::%player%}/100
            chance of {charityxD::%player%}%:
                loop all players:
                    set {charityrandom} to random number between 5000 and 19000000
                    add {charityrandom} to {balance::%loop-player's uuid%}
                loop all players:
                    send actionbar "&5&l(!) &bCharity &8»  &r%player% &dhas given &a$%formatNum({charityrandom})%&d to everyone!" to loop-player

        if level of mending of player's tool is more than 0:
            chance of .8949%:
                loop blocks in radius 4 around event-block:
                    if "%region at loop-block%" contains "mine":
                        add 1 to {loopblock::%player%}
                        set loop-block to air



                        
                set {explosivestuff::%player%} to level of fortune of tool of player*{loopblocks::%player%}*{multiplier::%player's uuid%}
                add {explosivestuff::%player%} to {balance::%player's uuid%}
                show large explosion at the event-block
                play sound "ENTITY_GENERIC_EXPLODE" with volume 4 to the player 
        chance of 4.5%:  
            execute command "/scoreboardrl %player%"
            if level of lure of player's tool is less than 1:
                if {globalboostertoken} is set:
                    set {randomtokens::%player%} to random number between 1000 and 10000
                    send action bar "&5You found &d%{randomtokens::%player%}% &5tokens" to player
                    add {randomtokens::%player%} to {token::%player's uuid%} 
                    stop
                set {randomtokens::%player%} to random number between 500 and 5000
                send action bar "&5You found &d%{randomtokens::%player%}% &5tokens" to player
                add {randomtokens::%player%} to {token::%player's uuid%}
            if level of lure of player's tool is more than 0:
                if {globalboostertoken} is set:
                    set {randomtokens::%player%} to random number between 15000 and 10000
                    set {randomtokens::%player%} to {randomtokens::%player%}*level of lure of player's tool/45
                    send action bar "&5You found &d%formatNum({randomtokens::%player%})% &5tokens" to player
                    add {randomtokens::%player%} to {token::%player's uuid%}
                    stop
                set {randomtokens::%player%} to random number between 7500 and 5000
                set {randomtokens::%player%} to {randomtokens::%player%}*level of lure of player's tool/45
                send action bar "&5You found &d%formatNum({randomtokens::%player%})% &5tokens" to player
                add {randomtokens::%player%} to {token::%player's uuid%}
            execute command "/scoreboardrl %player%"
        chance of .75345%:  
            if level of smite of player's tool is more than 0:
                set {randommoney::%player%} to random number between 5000 and 1000000
                set {randommoney::%player%} to {randommoney::%player%}*level of smite of player's tool/17.5
                send "&5&l(!) &dYou found &a&l$%formatNum({randommoney::%player%})% &dfrom Merchant"
                add {randommoney::%player%} to {balance::%player's uuid%}
            execute command "/scoreboardrl %player%"
        chance of .4902347983274239872836529873562983572390572398572398757239877239875723985723985723985%:
            if level of punch of player's tool is more than 0:
                set {_y} to event-block's y coordinate
                set {jackhammeramount::%player%} to 2*level of punch of player's tool
                loop blocks in radius {jackhammeramount::%player%} around event-block:
                    if y coordinate of loop-block = {_y}:
                        if "%region at loop-block%" contains "mine":
                            add 1 to {loopblocks::%player%}
                            show 10 smoke particle at the loop-block
                            set loop-block to air
                        add level of fortune of tool of player*{loopblocks::%player%}*{multiplier::%player's uuid%}/30 to {balance::%player's uuid%}

                loop 10 times:
                    play sound "ITEM_SHIELD_BREAK" with volume 6 to the player 

                    




on join:
    if {multiplier::%player's uuid%} is not set:
        set {multiplier::%player's uuid%} to 1




on join:
    execute command "scoreboardrl %player%"  

# -----------------------  A-Z Sell  ---------------------------------

on block break of stone:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 2*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 2*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}


on block break of coal ore:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 4*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 4*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of coal block:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 6*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 6*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of iron ore:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 8*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 8*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of iron block:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 10*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 10*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of gold ore:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 12*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 12*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of gold block:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 14*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 14*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of end stone:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 16*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 16*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of end stone bricks:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 18*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 18*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of lapis ore:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 20*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 20*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}


on block break of lapis block:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 22*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 22*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of diamond ore:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 24*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 24*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of diamond block:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 26*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 26*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of emerald ore:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 28*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 28*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of emerald block:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 30*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 30*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of quartz block:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 32*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 32*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

on block break of nether bricks:
    if world of player is not "season2":
        stop
    if "%region at event-block%" contains "mine":
        if {globalboostermoney} is set:
            cancel event
            add 34*level of fortune of tool of player*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 34*level of fortune of tool of player*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}

# -----------------------  A-Z Sell  ---------------------------------

#-----------------------  Donator Sell  ---------------------------------

on block break of blue terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if player has permission "divine.core":
        if {globalboostermoney} is set:
            add 500*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 500*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &r&lMilkyway+ &dto mine in here"

on block break of white terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if player has permission "milkyway.core":
        if {globalboostermoney} is set:
            add 1000*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 1000*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &r&lMilkyway+ &dto mine in here"

on block break of light blue terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if player has permission "space.core":
        if {globalboostermoney} is set:
            cancel event
            add 1500*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 1500*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &9&lSpace+ &dto mine in here"

on block break of orange terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if player has permission "milkyway.core":
        if {globalboostermoney} is set:
            add 2000*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 2000*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &6&lGalaxy+ &dto mine in here"

on block break of red terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if player has permission "milkyway.core":
        if {globalboostermoney} is set:
            cancel event
            add 2500*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 2500*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &c&lCosmo+ &dto mine in here"

on block break of purple terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if player has permission "milkyway.core":
        if {globalboostermoney} is set:
            add 3000*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 3000*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &5&lUniverse &dto mine in here"

on block break of gray terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if player has permission "milkyway.core":
        if {globalboostermoney} is set:
            add 3500*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 3500*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &9&lVoid &dto mine in here"

#-----------------------  Donator Sell  ---------------------------------

#-----------------------  Prestige Sell  ---------------------------------


on block break of green glazed terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if {prestige::%player's uuid%} is more than 0:
        if {globalboostermoney} is set:
            add 45*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 45*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &2P1+ &dto mine in here"

on block break of cyan glazed terracotta:
    if world of player is not "season2":
        stop
    if {prestige::%player's uuid%} is more than 99:
        if {globalboostermoney} is set:
            cancel event
            add 55*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            cancel event
            add 55*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &2P100+ &dto mine in here"

on block break of purple glazed terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if {prestige::%player's uuid%} is more than 199:
        if {globalboostermoney} is set:
            add 65*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 65*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &2P200+ &dto mine in here"

on block break of red glazed terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if {prestige::%player's uuid%} is more than 299:
        if {globalboostermoney} is set:
            add 75*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 75*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &2P300+ &dto mine in here"

on block break of black glazed terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if {prestige::%player's uuid%} is more than 399:
        if {globalboostermoney} is set:
            add 85*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 85*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &2P400+ &dto mine in here"

on block break of brown glazed terracotta:
    if world of player is not "season2":
        stop
    cancel event
    if {prestige::%player's uuid%} is more than 499:
        if {globalboostermoney} is set:
            add 95*level of fortune of player's tool*{multiplier::%player's uuid%}*2 to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
        if {globalboostermoney} is not set:
            add 95*level of fortune of player's tool*{multiplier::%player's uuid%} to {balance::%player's uuid%}
            execute command "scoreboardrl %player%"  
            set block to air
            clear {loopblock}
    else:
        send "&5&l(!) &dYou must be &2P500+ &dto mine in here"
















